name: 'Build my totem 7racker keymap'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["seeeduino_xiao_ble"]'
      shield: '["totem_7racker_dongle","totem_7racker_left","totem_7racker_left_peripheral","totem_7racker_right"]'
      alphas: '["Colemak"]'
      clipboard: '["Mac"]'
      custom_config: '["#define MIRYOKU_TAP_QWERTY"]'
      branches: '["zmkfirmware/zmk/main"]'
